### ISSUE TITLE
Error installing from nom

### ISSUE THREAD

**Issue by josete89** [purescript/documentation#117]
35778 verbose stack Error: purescript@0.11.6 postinstall: `node lib/install.js`
35778 verbose stack Exit status 1
35778 verbose stack     at EventEmitter.<anonymous> (/Users/alcaljos/.nvm/versions/node/v7.10.1/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
35778 verbose stack     at emitTwo (events.js:106:13)
35778 verbose stack     at EventEmitter.emit (events.js:194:7)
35778 verbose stack     at ChildProcess.<anonymous> (/Users/alcaljos/.nvm/versions/node/v7.10.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
35778 verbose stack     at emitTwo (events.js:106:13)
35778 verbose stack     at ChildProcess.emit (events.js:194:7)
35778 verbose stack     at maybeClose (internal/child_process.js:899:16)
35778 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
35779 verbose pkgid purescript@0.11.6

**Comment by garyb** [comment]
Please open an issue on https://github.com/purescript-contrib/node-purescript-bin rather than this repo. Also, there should be more to the error than that - it doesn't seem to contain much useful information :smile:
