### ISSUE TITLE
Using npm to install PureScript fails on Arch Linux

### ISSUE THREAD

**Issue by winksaville** [purescript/documentation#119]
It fails by hanging after saying purs isn't working:
```
$ npm install -g purescript
/home/wink/.npm-global/bin/purs -> /home/wink/.npm-global/lib/node_modules/purescript/bin/purs.js

> purescript@0.11.6 postinstall /home/wink/.npm-global/lib/node_modules/purescript
> node lib/install.js

  ⚠ The `/home/wink/.npm-global/lib/node_modules/purescript/vendor/purs` binary doesn't seem to work correctly
  ⚠ pre-build test failed
  ℹ compiling from source
```
The problem is Arch uses ncurses6 where as PS is using ncurses5. I was able to build PS from sources and that worked, but then when I tried to use `pulp init` it failed saying it couldn't find libtinfo.so.5. The solution ncurses 5 was to install [ncurses5-compat-libs](https://aur.archlinux.org/packages/ncurses5-compat-libs/) after doing so now `pulp init` worked with my `purs` compiled from sources.

I then guessed that maybe the reason the `npm install -g purescript` failed was because I was missing ncurses5. So I removed `purs` from my $PATH and reran `npm install -g purescript` and it worked!

So I'd like to suggest the npm instructions in [website](http://www.purescript.org/) and [Getting Started](https://github.com/purescript/documentation/blob/master/guides/Getting-Started.md) page be updated to reflect this information. I can take a stab at updating Getting-Started.md if you'd like.

**Comment by hdgarrood** [comment]
Is it worth statically linking ncurses in the prebuilt binaries? That way, we wouldn't need to expand the documentation as this problem wouldn't arise in the first place.

**Comment by hdgarrood** [comment]
Incidentally we do have some docs about ncurses in INSTALL.md in the compiler repo; if we do need to change the getting started guide I'd rather just say "if you have any problems installing the compiler, go here" and link to INSTALL.md.

**Comment by winksaville** [comment]
Static linking sounds like a good idea. It would also be helpfull if the `npm install` didn't hang bug actually gave you an error message so you might be able to find a solution, I've installed a quite a few npm packages and this was the first time its ever hung so hopefully that can be improved.

**Comment by wsdjeg** [comment]
@winksaville Thanks for your info, after run `sudo pacman -S ncurses5-compat-libs`, it works.

**Comment by winksaville** [comment]
Yep, installing ncurses5-compat-libs does make it work, as I noted in the original post. Also, I see that INSTALL.md has always stated the need for ncurses5. I'd still suggest updating Getting Started with pre-requesites or statically linking with ncurses5 as suggested by others. But because the info is in INSTALL.md I'll close this.

**Comment by ianliu** [comment]
@wsdjeg and @winksaville there is no `ncurses5-compat-libs` in the official Arch repository, it is an AUR package, so I don't know how @wsdjeg made it work with that command. I would suggest reopening this issue.

**Comment by beiranvand-karim** [comment]
> @wsdjeg and @winksaville there is no `ncurses5-compat-libs` in the official Arch repository, it is an AUR package, so I don't know how @wsdjeg made it work with that command. I would suggest reopening this issue.

Yeah, I have the same problem

**Comment by hdgarrood** [comment]
Does installing the ncurses5-compat-libs AUR package fix the issue?

Also, what happens with npm install -g exactly? Does it produce exactly the output given in the original issue description (and no more)? Also, when the npm package decides to build from source, does it give you the output from stack? How much time did you give it before giving up? (There are quite a few dependencies to install so it might just be that it’s slow)

**Comment by gakada** [comment]
Both `yarn` and `npm` installs worked for me after installing `ncurses5-compat-libs` from AUR (it was complaining about missing `libtinfo.so.5` before that). Though that is still inconvenient:
- There is no officially supported way to install AUR packages AFAIK
- `ncurses5-compat-libs` also requires to add a GPG key manually (as mentioned [here](https://aur.archlinux.org/packages/ncurses5-compat-libs#pinned-547799))
- It also downloads from ftp.gnu.org which is known to be down frequently (had to manually download the files).
