### ISSUE TITLE
Docs: "Overlapping instances are currently permitted" --- still true, or outdated?

### ISSUE THREAD

**Issue by metaleap** [purescript/documentation#121]
https://github.com/purescript/documentation/blob/master/language/Type-Classes.md says:

> Overlapping instances are currently permitted but not recommended.

I get a compiler error-not-warning on an overlapping-instances situation, but from the above I the user can't tell for sure if this is now always an error, or whether there might be overlapping-instances cases still being permitted-but-warned-about. Thx!

**Comment by paf31** [comment]
The released compiler should warn, not error. The change to make overlaps into an error is on master, but unreleased.

**Comment by metaleap** [comment]
Yeah I'm using forked `master`, so I take it overlapping-instances are out throughout, going forward?

**Comment by paf31** [comment]
Closing as this is currently accurate.
