### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by paf31** [purescript/documentation#124]
This is a bit of a disaster from a licensing perspective. As I understand it, the content of every accepted PR is All Rights Reserved by its original author. This means users only have the rights ensured by the GitHub TOS, such as to view, fork, etc. but not to use the content for any purpose, and not to redistribute it.

I would have liked this content to be permissively licensed, but it's a bit late now.

This leaves us with a few options:

- Start over with a fresh license. Obviously this isn't ideal, but I wouldn't be against it if I had more time or more help to rewrite stuff. We might be able to salvage older versions of bits of content if they were moved from old repos with licenses.
- Try to get previous contributors to explicitly license their content like we did with the compiler repo. We know how that went, and it took a long, long time, and was never even finished. Fortunately, I believe the GitHub terms save us there, since we did have a LICENSE file at least, and users are required to license their PR'd code under the same terms. The same does not apply here, however.

Whatever we do, I would like to start requiring explicit licensing in some form for new contributions.

**Comment by hdgarrood** [comment]
I think a combination of these is probably the way to go: try to get previous contributors to explicitly license their content, and rewrite any parts whose authors we can't get in touch with. I would guess that it would only take a few people to explicitly license their contributions to get this repo into a stage where the vast majority of the content is permissively licensed.

Do we maybe want a CONTRIBUTORS.md file like in the compiler?

**Comment by paf31** [comment]
Yes I think that's the way to go.

**Comment by hdgarrood** [comment]
We now have a CONTRIBUTORS.md file which means that most of the content here is now licensed, but in order to fully address this issue we still need someone to go through the contributors tab and/or git history and get consent from any remaining contributors, or alternatively to delete any remaining unlicensed content, to ensure that everything is covered.
