### ISSUE TITLE
i can't get particular value from API object response  

### ISSUE THREAD

**Issue by Rakesh1988Rakesh** [purescript/documentation#125]
I am fetching api responce as a:

result = studentInfo: StudentInfo 
		{
			department : ["Account", "Register", "Sport", "Social", "Hostel"]
			,branch : {id : "001",name : "IT", count: 50 , year :2017}
		}

and i will try to get only count value from branch and assing to simple number variable, but we can't get count value.

i am tring to get count value as a:
 result.branch{count}
 result.branch.count
 result{branch{count}}
 result{branch.count}
 
but its shows error "Could not match type" 
 
how to get count value in purescript code.
please help me to resolved that issue.

**Comment by paf31** [comment]
`result.branch.count` is the correct syntax. Please use StackOverflow for this sort of question in future.
