### ISSUE TITLE
In Pursuit, what does "S to focus" mean?

### ISSUE THREAD

**Issue by marick** [purescript/documentation#139]
If you go to https://pursuit.purescript.org, the search bar says "Search for packages, types, functions... (S to focus)" 

<img width="653" alt="screen shot 2017-11-08 at 5 15 12 pm" src="https://user-images.githubusercontent.com/71909/32579884-70805ae0-c4a8-11e7-8031-694897dca3b3.png">

I don't know what "S to focus" means. Perhaps it means "just focus on packages and functions" but I can't really grok (as a newbie coming from Elm) what it's actually doing.

**Comment by garyb** [comment]
It means if you press the S key it puts the focus in the search box, so you can hit S and type whenever you are on the site to start searching for something new... I guess. It's a feature I have never used :wink:.

**Comment by marick** [comment]
Huh. I wouldn't have guessed.

Wouldn't HTML5 autofocus be better? There's no other candidate on the page for a default focus.

**Comment by justinwoo** [comment]
I hit spacebar often to scroll down on pursuit. Autofocusing by default would at least annoy me a bit.

**Comment by hdgarrood** [comment]
Indeed. Another reason not to autofocus is that it might break links which include fragments (ie to link to a specific declaration on the page, which might no longer be visible if the search box is autofocused).

**Comment by marick** [comment]
Autofocus was a side issue. I still suggest revising the message to say "(Type S to put focus in this field)"
