### ISSUE TITLE
Change Help link at pursuit.purescript.org to point to user help

### ISSUE THREAD

**Issue by marick** [purescript/documentation#140]
The banner at Pursuit has a `Help` link:

<img width="869" alt="screen shot 2017-11-08 at 5 20 33 pm" src="https://user-images.githubusercontent.com/71909/32580068-3ee863dc-c4a9-11e7-89d5-7e90143c8c72.png">

It goes to help for *package maintainers*. I suggest it go to help for Pursuit users, so that they know, for example, that you should search for `Data.String` rather than `String`.

I would be *very* happy to write that help page, if paired with someone who knows how Pursuit works.

The "Publish" sidebar text and link are good and, I think, sufficient.

**Comment by paf31** [comment]
Could you please reopen this as an issue on `purescript/pursuit`?
