### ISSUE TITLE
Needed: an Elm transition guide

### ISSUE THREAD

**Issue by marick** [purescript/documentation#142]
I suggest a guide for people considering moving from Elm to PureScript. I volunteer to be primary author. I will need advice and reviewers.

Tentative table of contents:

1. Language differences (possibly just point to various pages that already exist).
2. Using the repl like you're used to. (This would include a pre-baked configuration that made the repl look as close to the Elm repl as possible.)
3. Common Elm idioms, translated into PureScript.
4. Simple application-building support (the equivalent of elm-reactor).
5. How to use Pursuit. What's a good workflow for finding the package you want?
5. How to get the information you're used to out of API documentation.
5. How to build the equivalent of an Elm Architecture app (reimplement Elm tutorial app). 
6. Glossary for jargon

**Comment by hdgarrood** [comment]
I don't want to attempt to maintain such a thing here. I'd be very happy for something like this to exist but I don't think we have the resources for something like this right now.

Did you see https://github.com/alpacaaa/elm-to-purescript-cheatsheet by the way?

**Comment by marick** [comment]
I will then host it on a site of mine. I'll still need help to do an efficient/good job.

I've seen that cheat sheet as well as several others. They're very helpful, but note the bullet points above that they do not cover.

**Comment by paf31** [comment]
Agreed, this would be a valuable resource, but doesn't really belong here. Let's move this conversation to Slack or some other channel, thanks.
