### ISSUE TITLE
Filling out the CONTRIBUTORS.md file

### ISSUE THREAD

**Issue by hdgarrood** [purescript/documentation#151]
This repository is currently not in the best position with respect to licensing; see #124 for background.

We have now started a CONTRIBUTORS.md file in the same style as the one in the compiler repository, and we are trying to get it filled out a bit, so that as much of this repository as possible is explicitly licensed.

Instead of having you all send PRs, which will inevitably cause lots of merge conflicts, I'd really appreciate it if you could comment on this issue to confirm that you're happy to license your contributions under the terms of [CC BY-NC-SA 3.0](https://creativecommons.org/licenses/by-nc-sa/3.0/deed) (or some other license if you prefer; we recommend CC BY-NC-SA over MIT or any other software licenses you might be more familiar with, because it makes more sense for written work). I (or some other maintainer) can then update the CONTRIBUTORS.md file appropriately.

I've heard GitHub doesn't like it when you tag lots of people at once so I'll just start from the beginning of the Contributors tab: @paf31 @garyb @chexxor @andyarvanitis @jdegoes @epost @joseanpg @jplatte @Fresheyeball @Thimoteus @kRITZCREEK @puffnfresh @alexchandel @nwolverson @dgendill @Xandaros @stefanholzmueller @haf @csicar @damncabbage

**Comment by jplatte** [comment]
CC BY-NC-SA 3.0 sounds good to me! By the way, in GitHub-flavored Markdown, you can make the list a checklist like this:

```markdown
- [x] user 1
- [ ] user 2
- [ ] ...
```

Might make sense to do for this.

**Comment by garyb** [comment]
👍 from me

**Comment by nwolverson** [comment]
This is fine.

**Comment by csicar** [comment]
I am also fine with the license

**Comment by andyarvanitis** [comment]
Fine for me, thanks

**Comment by jdegoes** [comment]
👍

**Comment by epost** [comment]
👍

**Comment by paf31** [comment]
👍

**Comment by kRITZCREEK** [comment]
I'm fine with the license.

**Comment by stefanholzmueller** [comment]
Sounds good.

**Comment by damncabbage** [comment]
I'm happy to license.

**Comment by dgendill** [comment]
I'm fine with the license.

**Comment by haf** [comment]
I'm fine with the license.

**Comment by Xandaros** [comment]
Lol, I have changed a grand total of 1 line.
Yes, I'm fine with the license. Do what you want with my line ;)

**Comment by kika** [comment]
my net contribution is zero, but I'm fine with the license 👍 

@Xandaros it is the addition that matters, you normally don't license your deletes :-)

**Comment by chexxor** [comment]
I accept that license. :+1:

**Comment by hdgarrood** [comment]
I think the licensing issue is not yet completely addressed, since I believe there are still a few unlicensed contributions (although they are all fairly minor). It probably does make sense to close this now though.
