### ISSUE TITLE
Document `derive newtype` syntax and capability

### ISSUE THREAD

**Issue by chexxor** [purescript/documentation#155]
I can't find documentation for `derive newtype` syntax in this repo, and it should be added.

**Comment by JordanMartinez** [comment]
Here's a summary of instance deriving and newtype deriving:
- https://github.com/JordanMartinez/purescript-jordans-reference/blob/latestRelease/11-Syntax/01-Basic-Syntax/src/03-TypeClasses-and-Newtypes/21-Deriving-Common-Typeclass-Instances-for-Custom-Types.purs
- https://github.com/JordanMartinez/purescript-jordans-reference/blob/latestRelease/11-Syntax/01-Basic-Syntax/src/03-TypeClasses-and-Newtypes/22-Deriving-Typeclass-Instances-for-Newtyped-Types.purs

These just summarize what was already stated in 24 days of Purescript
