### ISSUE TITLE
Installing purescript on windows behinid a corporate firewall

### ISSUE THREAD

**Issue by noiseOnTheNet** [purescript/documentation#162]
Hi, I have problems installing purescript behind a corporate proxy on windows.

`npm config set strict-ssl false`

does not work for me.
I read a lot of comments about adding certificates but can't figure out where to download pem files.

`npm config set registry "http://registry.npmjs.org/"`

helps a little more; I've been able to install pulp and bower; unfortunately, install-purescript fails with a message saying:

> Error: unable to get local issuer certificate

After many trying I resorted to downloading the windows bundle and unpacked it.
If I do purs repl I get 

> purs repl: No input files; try running `pulp psci` instead.

Please help me let all things work.
Thank you,
    Marco

**Comment by kRITZCREEK** [comment]
Since you've downloaded the binary and you've managed to download pulp you should just be able to run `pulp repl`.

If downloading the `purescript` npm package through a proxy doesn't work, that's an issue for https://github.com/purescript-contrib/node-purescript.
