### ISSUE TITLE
Record documentation doesn't show how to update capitalized fields

### ISSUE THREAD

**Issue by oconnore** [purescript/documentation#169]
In purescript-aws-ec2, there is a newtype that looks like
```
newtype Request = Request { "DryRun": NullOrUndefined Boolean, ...}
```

All of these barf in one way or another:
```
instance {DryRun = NullOrUndefined (Just true)}
instance {"DryRun" = NullOrUndefined (Just true)}
```

I assume that purescript can update capitalized record fields, since this code is being written (haskell just wouldn't allow the record fields...). Can the docs show how to do this?

Also, is there a nicer way to access capitalized record fields other than `let Type { "Str": a } = instance in a`? The `instance.field` syntax apparently disallows capitalized fields.

**Comment by chexxor** [comment]
@oconnore, may I ask why you closed this? This seems like it would be a nice addition to the language/Records.md file.

**Comment by LiamGoodacre** [comment]
@oconnore `inst."DryRun"` should work for field access with capitalization.
