### ISSUE TITLE
Get ready for devdocs

### ISSUE THREAD

**Issue by abhisekp** [purescript/documentation#170]
- [ ] Add a license file to the docs https://trello.com/c/PVnfdeaN/26-suggest-new-docs-here

- [x] Become more popular [5k :stars: s] :sweat_smile: 
  https://github.com/purescript/purescript

**Comment by garyb** [comment]
The contributions to the docs are licensed at least: https://github.com/purescript/documentation/blob/master/CONTRIBUTORS.md (CC BY-NC-SA), does that count? :wink:

**Comment by hdgarrood** [comment]
I'm going to close this as we already have #124 for tracking the licensing issue.
