### ISSUE TITLE
Re-organize directories to Divio docs recommendations?

### ISSUE THREAD

**Issue by chexxor** [purescript/documentation#182]
As part of the ["Ideas for improving PS documentation?" Discourse discussion](https://purescript-users.ml/t/ideas-for-improving-ps-documentation/165/4), the idea was raised to follow the documentation recommendations used by Divio. It seems like a good idea to me.

If we want to start moving to follow their recommendations, I think the best way to start would be to create new directories, one for each kind of documentation: "Tutorials", "How-to guides", "Explanation", and "Reference" and put a template of the desired doc page into each directory. Then, we can bit-by-bit migrate doc pages from the other directories to there.

**Comment by hdgarrood** [comment]
I don’t think that would be an improvement, actually. I think it’s a useful framework, and definitely worth bearing in mind while you’re writing docs, but I don’t think we should go as far as to rearrange everything in here to fit into that categorisation.

**Comment by chexxor** [comment]
My goal with this proposal:
1) Give newcomers a clear place to puts docs which help those following behind them.
2) Give people a template to follow when writing docs to mitigate the complexities of doc-writing.

Before we can provide a template, there needs to exist a specific kind of doc page for it to be a template for.

Having a doc template has proven to be very effective for the errors docs - they see far more brand new documentation than anywhere else in this documentation project. All other changes in the last several months has been url fixes and minor detail fixes. I want to help people contribute more brand new docs, and I think having templates and doc page stubs would help a lot.

The directory names aren't terribly important right now, I agree, but if the content in a directory doesn't fit the template, I think they should be revised to fit it.

@hdgarrood Would you be ok with having this be a template-driven documentation project? I think that's what I'm proposing here.

**Comment by hdgarrood** [comment]
> Having a doc template has proven to be very effective for the errors docs

To me, your argument here is not strong enough to justify rearranging this repo. I think a more plausible explanation is that errors docs are easier to write than other pages in general, and also that they're more visibly incomplete (especially because the compiler generates links to the error pages when the relevant error occurs).

I think the current layout makes more sense. (Note, however, that I would like to move most of the `guides/` directory into the libraries that they concern; see #96).

**Comment by chexxor** [comment]
I'm not saying we need to rearrange the repo, like I said in my previous post.

> The directory names aren't terribly important right now, I agree

I just want baby-steps right now. I want to make a place to put tutorials and explanations. I want to put a template doc for all of these directories. And I'd like to update the readme to explain the various types of docs in this repo. I'd like to make a contributors doc which walks people through the various types of docs, where their doc belongs, and how to use the template.

**Comment by hdgarrood** [comment]
Since we decided that the scope of this repo should be more restricted, I think this issue can be closed.
