### ISSUE TITLE
Errors in "Getting Started with Purescript"

### ISSUE THREAD

**Issue by senorsmile** [purescript/documentation#187]
I'm trying out purescript for the first time.  

I'm attempting to follow the docs: 
https://github.com/purescript/documentation/blob/master/guides/Getting-Started.md

Things seem to install OK.  I can pulp init and successfully run tests.  

When I try to install purescript-lists, I get multiple options: 
```
bower install purescript-lists --save

Unable to find a suitable version for purescript-prelude, please choose one by typing one of the numbers below:
    1) purescript-prelude#3.3.0 which resolved to 3.3.0 and is required by install_test
    2) purescript-prelude#^3.0.0 which resolved to 3.3.0 and is required by purescript-eff#3.2.1
    3) purescript-prelude#^4.0.0 which resolved to 4.0.1 and is required by purescript-bifunctors#4.0.0, purescript-control#4.0.0, purescript-distributive#4.0.0, purescript-effect#2.0.0, purescript-either#4.0.0, purescript-foldable-traversable#4.0.0, purescript-identity#4.0.0, purescript-invariant#4.0.0, purescript-lazy#4.0.0, purescript-lists#5.0.0, purescript-maybe#4.0.0, purescript-newtype#3.0.0, purescript-nonempty#5.0.0, purescript-orders#4.0.0, purescript-refs#4.1.0, purescript-tailrec#4.0.0, purescript-tuples#5.0.0, purescript-unfoldable#4.0.0

```

There are a few more of these choices.  Regardless of which combo I pick, it always ends up in a state where running pulp repl errs out with:

```
pulp repl

Error found:
at bower_components/purescript-either/src/Data/Either/Inject.purs line 16, column 1 - line 16, column 1

  Unable to parse module:
  unexpected "else"
  expecting declaration or end of input


See https://github.com/purescript/documentation/blob/master/errors/ErrorParsingModule.md for more information,
or to contribute content related to this error.

```

Is this a problem or am I doing something very wrong?

**Comment by justinwoo** [comment]
Seems like you have the wrong version of PureScript installed anyway, the current version is 0.12

**Comment by senorsmile** [comment]
> Seems like you have the wrong version of PureScript installed anyway, the current version is 0.12

You are right.  I'm not too familiar with npm.  Simply following the docs ended up with 0.11.7.  Perhaps that's the source of the problem?

**Comment by RamiroPastor** [comment]
I'm trying purescirpt for the first time too, and cannot even install it:

```
ramiro@LifeOnMars:~$ sudo npm install -g purescript
[sudo] password for ramiro: 
/usr/local/bin/purs -> /usr/local/lib/node_modules/purescript/purs.bin

> purescript@0.12.0 postinstall /usr/local/lib/node_modules/purescript
> install-purescript --purs-ver=0.12.0 .

✔ Check if a prebuilt 0.12.0 binary is provided for Linux (1s)
✖ Download the prebuilt PureScript binary
  https://github-production-release-asset-2e65be.s3.amazonaws.com/13206906/5a05…
  Error: EACCES: permission denied, open 'purs.bin'
▬ Verify the prebuilt binary works correctly
▬ Save the downloaded binary to the cache directory

↓ Fallback: building from source

✔ Check if 'stack' command is available
  1.7.1 found at /usr/local/bin/stack
✖ Download the PureScript 0.12.0 source
  Error: EACCES: permission denied, mkdtemp '/usr/local/lib/node_modules/purescr
ipt/node-purescript-mJWcuq'
▬ Ensure the appropriate GHC is installed
▬ Build a binary from source
▬ Save the built binary to the cache directory

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! purescript@0.12.0 postinstall: `install-purescript --purs-ver=0.12.0 .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the purescript@0.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ramiro/.npm/_logs/2018-06-26T15_10_22_034Z-debug.log

```

The log file has 3k lines so i won't copy it.

**Comment by BebeSparkelSparkel** [comment]
The getting started is definitely out of date
These were great resource that got me around the bower problem with purescript 0.12.0  

[Transition from 0.11.7 -> 0.12.0 differences](https://purescript-users.ml/t/working-with-0-11-7-in-a-0-12-world/180)
* With the release of 0.12 we have a situation where many commonly used libraries (e.g. Halogen) and tools (e.g. Pulp) are incompatible with the latest version of the compiler.

[Installing psc-package](https://www.npmjs.com/package/psc-package-bin-simple)
```shell
npm i -g psc-package-bin-simple
```

[Initialize project with psc-package](https://github.com/purescript-contrib/pulp#dependency-management)
```shell
pulp --psc-package init
```

[Using psc-package](https://psc-package.readthedocs.io/en/latest/usage.html)

**Comment by LucianU** [comment]
@BebeSparkelSparkel, I'm trying to access the first link in your post, but it redirects me to an essay-writing service.

**Comment by BebeSparkelSparkel** [comment]
@LucianU looks like it has been taken down

**Comment by garyb** [comment]
The domain got snagged, updating the links to https://discourse.purescript.org/ should work.

**Comment by BebeSparkelSparkel** [comment]
@garyb thanks. @LucianU fixed the link

**Comment by LiamGoodacre** [comment]
Closing as the original issue appears solved.
