### ISSUE TITLE
Remove "Project scope" text from the beginning

### ISSUE THREAD

**Issue by anttih** [purescript/documentation#194]
This section is for people who contribute to this repo but not at all useful for the 80% use case which is to read the docs. You can easily see the scope of the documentation by looking at the links and topics on the README. I suggest we move this section to the very bottom of the README or extract that to a separate page and link to it.

**Comment by hdgarrood** [comment]
I disagree; it's useful for people to know what they can expect to find in here, surely?

**Comment by anttih** [comment]
It is useful, but my point is that we should try and organize the README so that it is apparent just by reading the actual docs what the docs contain. Right now, the scope section is just listing the same stuff that we have further down the document. If we move the most important stuff like the guides to the top, it becomes even more redundant to list those at the beginning.

I just think it's bad UI for readers to see a "Project scope" when all they want to read are the actual docs.

**Comment by hdgarrood** [comment]
Okay, sure, that makes sense. Moving it to the bottom of the readme sounds sensible to me.

**Comment by chexxor** [comment]
Addressed with https://github.com/purescript/documentation/pull/223
