### ISSUE TITLE
Duplicated / spread out information

### ISSUE THREAD

**Issue by hdgarrood** [purescript/documentation#2]
The FFI:

* http://www.purescript.org/learn/ffi/ seems to be the best resource.
* The FFI section from the Language Guide (which is now here: <https://github.com/purescript/documentation/blob/master/language/FFI.md>) does not seem very helpful.
* The 'How to implement a foreign function with a constraint' file in this repo covers ideas which were already covered in the purescript.org tutorial
* The 'FFI tips' file in this repository has a small amount of overlap with the purescript.org tutorial.

**Comment by paf31** [comment]
In general, I think we can pretty aggressively combine or reduce any duplicate sources of data now that the documentation will be under a repository.

**Comment by hdgarrood** [comment]
Now that the website has been reduced down to a single page, I think we can close this.
