### ISSUE TITLE
Clarifying licensing status of guides

### ISSUE THREAD

**Issue by hdgarrood** [purescript/documentation#228]
Hi @soupi, @kika, @shuhei, @narrative, @mseri, @owickstrom!

A while ago, you all contributed to at least one of the articles on the purescript.org website, https://github.com/purescript/purescript.github.io/ -- thanks again for those contributions! (Those guides have since moved here.)

As far as I'm aware, we didn't ask you to license your contributions to us at the time, which puts us in slightly awkward territory with respect to what we're allowed to do with the content.

A little while ago, we started notifying contributors to ask them if they would license their contributions under the terms of [CC BY-NC-SA 3.0](https://creativecommons.org/licenses/by-nc-sa/3.0/deed) (see #151). We didn't get quite as far as asking you back then. Now we'd like to move some of these guides into library documentation (see #96) which means now is a good time to ask. Would you be happy to license your contributions under these terms? A :+1: comment will suffice: please don't send PRs to CONTRIBUTORS.md because we'll end up with merge conflicts that way. Thanks very much!

See also #124.

**Comment by mseri** [comment]
It is perfectly fine with me

**Comment by narrative** [comment]
:+1: from me. Thanks for checking!

**Comment by shuhei** [comment]
:+1:

**Comment by owickstrom** [comment]
👍

Den sön 13 jan. 2019 11:17 skrev Shuhei Kagawa <notifications@github.com>:

**Comment by kika** [comment]
Yep, AFAIK, I've contributed a whopping single line and got myself accepted into the Purescript Hall of Fame :-)

**Comment by soupi** [comment]
+1

**Comment by hdgarrood** [comment]
Perfect, thanks very much everyone!
