### ISSUE TITLE
Skolem Golem

### ISSUE THREAD

**Issue by bbarker** [purescript/documentation#246]
I feel like things got real after reading https://github.com/purescript/documentation/blob/master/language/Types.md#rank-n-types with the mention of a skolemized type; Wolfram mathworld explained what this meant in logic but am not exactly sure how this relates to the example at hand when considering the Curry-Howard isomorphism.

**Comment by hdgarrood** [comment]
My understanding is that the term "skolemized" refers to the way these things are implemented inside the type checker, and so is probably not worth mentioning there. I think we could safely just replace that with "rigid" (and perhaps clarify that it is the type variable bound by the `forall a` in the type annotation for `poly` too). Any thoughts @paf31?

**Comment by hdgarrood** [comment]
You might find https://github.com/purescript/documentation/blob/master/errors/EscapedSkolem.md useful as additional context.

**Comment by garyb** [comment]
@hdgarrood 👍 from me at least for using "rigid". I see skolemisation as an implementation detail.

**Comment by paf31** [comment]
I agree, "rigid" seems preferable.
