### ISSUE TITLE
Filling out CONTRIBUTORS.md some more

### ISSUE THREAD

**Issue by hdgarrood** [purescript/documentation#266]
Hi all. This repository does not currently have a license which covers all of its content; see #124 for background. We have a CONTRIBUTORS.md file in the same style as the one in the compiler repository, and I am trying to ensure that everyone's contributions are covered.

Instead of having you all send PRs, which will inevitably cause lots of merge conflicts, I'd really appreciate it if you could comment on this issue to confirm that you're happy to license your contributions under the terms of CC BY-NC-SA 3.0 (or some other license if you prefer; we recommend CC BY-NC-SA over MIT or any other software licenses you might be more familiar with, because it makes more sense for written work). I can then update the CONTRIBUTORS.md file appropriately.

I've gone through the contributors list on the repo, and I am pretty sure that after all of the following people are covered, we can consider this repo fully licensed, which would be great:

- [x] ~~@alexchandel~~ I checked again and these contributions are no longer in the repo
- [x] @Thimoteus
- [x] @archaeron
- [x] @parsonsmatt
- [x] @nicodelpiano
- [x] @cdepillabout
- [x] @bergmark
- [x] @spicydonuts
- [x] ~~@sellout~~ I checked again and these contributions are no longer in the repo
- [x] @clayrat
- [x] @tchajed
- [x] @stephencelis
- [x] ~~@paluh~~ I checked again and these contributions are no longer in the repo
- [x] @AidanDelaney 

I'm happy to answer any questions you might have.

**Comment by Thimoteus** [comment]
I confirm it's OK to license my contributions under the terms of CC BY-NC-SA 3.0.

**Comment by clayrat** [comment]
I confirm too.

**Comment by nicodelpiano** [comment]
I'm happy to license my contributions under the terms of CC BY-NC-SA 3.0.

**Comment by stephencelis** [comment]
I also confirm, thanks!

**Comment by tchajed** [comment]
I confirm that it's OK to license my contributions under the terms of CC BY-NC-SA 3.0.

**Comment by parsonsmatt** [comment]
I confirm!

**Comment by spicydonuts** [comment]
I confirm!

**Comment by cdepillabout** [comment]
I confirm :-)

**Comment by AidanDelaney** [comment]
I confirm that it's OK to license my contributions under the terms of CC BY-NC-SA 3.0.

**Comment by bergmark** [comment]
I confirm

**Comment by archaeron** [comment]
Sorry, missed this.
I confirm

**Comment by hdgarrood** [comment]
All done, thanks everyone!
