### ISSUE TITLE
Installation failed on ubuntu due to missing libtinfo.so.5

### ISSUE THREAD

**Issue by nakamin** [purescript/documentation#282]
Error message
`error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory`

Installing `libtinfo5` fixed it. Perhaps we can update the docs?

**Comment by hdgarrood** [comment]
This is documented in `INSTALL.md` which is in the root of the compiler repo, and is also included in the compiler binary bundles.

**Comment by nakamin** [comment]
I see, I was reading the getting started page... maybe it can be linked there?

**Comment by hdgarrood** [comment]
Yes, that's probably a good idea. I'd prefer that we statically link `libtinfo` in the prebuilt compiler binaries, though, so that this can't happen in the first place: https://github.com/purescript/purescript/issues/3696
