### ISSUE TITLE
Add <#> to "Differences from Haskell" page

### ISSUE THREAD

**Issue by GCrispino** [purescript/documentation#284]
I recently realized that Haskell's `<&>` operator is not present in Purescript as is. The equivalent is `<#>` or the `mapFlipped` function.

Should this be in the [Where is ... from Haskell?](https://github.com/purescript/documentation/blob/master/language/Differences-from-Haskell.md#where-is--from-haskell) section from the "Differences from Haskell" guide?

If so, I'd happily create a PR changing this.

**Comment by JordanMartinez** [comment]
Most likely.

**Comment by GCrispino** [comment]
Thanks for replying @JordanMartinez! I'll wait for the opinion of a maintainer.

**Comment by GCrispino** [comment]
Since no mantainer answered, I took the liberty of opening a PR (https://github.com/purescript/documentation/pull/285). Feel free to comment here or there. Kudos!

**Comment by hdgarrood** [comment]
Resolved by #285
