### ISSUE TITLE
Bower is deprecated but still recommended to install ?

### ISSUE THREAD

**Issue by flip111** [purescript/documentation#287]
https://github.com/purescript/documentation/blob/master/guides/Getting-Started.md#setting-up-the-development-environment

https://github.com/purescript/purescript/issues/3396

Should i install bower still ??

**Comment by natefaubion** [comment]
It is recommended you use `spago`. We will hopefully have these directions updated ASAP. Please see the in progress PR https://github.com/purescript/documentation/pull/286.
