### ISSUE TITLE
PureScript Unscripted

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [purescript/documentation#288]
Is this still being hosted? I tried to attend last month but no one joined the zoom meeting.

**Comment by chexxor** [comment]
I was the owner of that event for a few years. My personal life had become overwhelming early in 2019 so I had to stop creating those. I remember asking for help in a few places to get someone to take it from me, but I didn't get any answers.

Sorry if I didn't remove it from here!

**Comment by BebeSparkelSparkel** [comment]
No prob

**Comment by hdgarrood** [comment]
I guess we should remove it from the ecosystem.md file in this repo, then.
