### ISSUE TITLE
Remove pages

### ISSUE THREAD

**Issue by paf31** [purescript/documentation#3]
I think we can remove quite a few pages:

**Out of date/no longer necessary**

- 0.7/0.10 Migration Guide
- PureScript Conf 2015/2016
- Recommended Libraries (very out of date now, and no longer necessary now that we have the package set repo and Pursuit?)
- PureScript and Docker (not sure if this still works, but we should check)

**Belong elsewhere**

- PSCi (should be in the main repo as a README)
- Frequently asked `psc-ide` questions (same)
- How to implement a foreign function with a constraint (merge with FFI.md?)
- The Partial Type Class (on the website now - I'm fine with articles living here eventually, but let's pick one?)
- Documentation Admin (let's make issues for this)
- Wikipedia Page Proposal (this is still good, but as a draft, I'm not sure it belongs here)

**Comment by hdgarrood** [comment]
Great, thanks

**Comment by hdgarrood** [comment]
The PureScript and Docker page points to a docker image that only has psc up until 0.6.7.1: https://hub.docker.com/r/biscarch/purescript/tags/ so I think we can remove that, but I'll also put it in a gist and let the original author know it's there in case he still wants it for whatever reason.

**Comment by hdgarrood** [comment]
Is anyone going to see the PSCi page if we move it to the compiler repo as `psci/README.md` though? What about having a dedicated subdirectory in this repo with one page for each binary in the purescript package?

**Comment by hdgarrood** [comment]
Also, re 'The Partial type class' - I agree for picking one out of the website and here. Since there's more stuff here, shall we put it here? And same for the other guides on the website?

**Comment by joneshf** [comment]
> * 0.7/0.10 Migration Guide

I think the 0.10 guide is still relevant. It's only been out for a few months.

> * Recommended Libraries (very out of date now, and no longer necessary now that we have the package set repo and Pursuit?)

Part of the appeal of this list is the categories. Can Pursuit have categorization if this list goes away?

**Comment by hdgarrood** [comment]
I'm inclined to agree that the appeal is the categories. We do eventually want Pursuit to have some kind of categorization, see https://github.com/purescript/pursuit/issues/147, although I would like to keep the recommended libraries page at least for now - most of the libraries there have been kept up to date.
