### ISSUE TITLE
(Code) Style Guide

### ISSUE THREAD

**Issue by paf31** [purescript/documentation#30]
From https://github.com/purescript/roadmap/issues/49

Not to be confused with the style guide we have for library maintainers.

**Comment by chexxor** [comment]
Maybe simply adopt the style guide which @ianbollinger started?
https://github.com/ianbollinger/purescript-style-guide/blob/master/purescript-style.md

We can build on top of it.

**Comment by hdgarrood** [comment]
I'm going to declare this outside the scope of this repo; I don't think there is either interest or bandwidth among core maintainers to take this on.
