### ISSUE TITLE
Error in "Getting Started with PureScript"

### ISSUE THREAD

**Issue by danny-andrews** [purescript/documentation#304]
In the "Getting Started with PureScript" guide, everything runs fine until this step:

> Modify the test/Main.purs file, and add the following code:
```purescript
module Test.Main where

import Prelude

import Euler (answer)
import Test.Assert (assert)

main = do
  assert (answer == 233168)
```

When you run `spago test`, you get:
```
Error found:
in module Test.Main
at test/Main.purs:6:1 - 6:28 (line 6, column 1 - line 6, column 28)

  Module Test.Assert was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.
```

I'm assuming this is an external package that we have not told the user to download at this point.

**Comment by hdgarrood** [comment]
Could you double check that you ran `spago install assert` please?

**Comment by danny-andrews** [comment]
Whoops, I missed that step in the guide. Sorry for the noise!

**Comment by hdgarrood** [comment]
No worries, thanks for reporting anyway!

**Comment by tc-joegiralt** [comment]
So I had this issue after I ran

```bash
$ spago install assert
```

doing this fixed it
```bash
$ spago verify assert
```
