### ISSUE TITLE
Point "PuresScript by Example" links to book.purescript.org

### ISSUE THREAD

**Issue by kurtmilam** [purescript/documentation#315]
By my count, there are are five links in the documentation that point to the book on leanpub.

I'd be happy to open a PR if there's interest.

Pages with links to leanpub (may not be exhaustive):
- [README.md#project-scope](https://github.com/purescript/documentation#project-scope)
- [guides/FFI-Tips.md#why-doesnt-my-eff-work-when-passed-to-a-normal-js-function](https://github.com/purescript/documentation/blob/master/guides/FFI-Tips.md#why-doesnt-my-eff-work-when-passed-to-a-normal-js-function)
- [guides/FFI.md#conclusion](https://github.com/purescript/documentation/blob/master/guides/FFI.md#conclusion)
- [language/Type-Classes.md#multi-parameter-type-classes](https://github.com/purescript/documentation/blob/master/language/Type-Classes.md#multi-parameter-type-classes)
- [language/Type-Classes.md#functional-dependencies](https://github.com/purescript/documentation/blob/master/language/Type-Classes.md#functional-dependencies)

**Comment by hdgarrood** [comment]
Yes please!

**Comment by thomashoneyman** [comment]
This can be closed now that #316 has been merged.
