### ISSUE TITLE
Unable to install purescript using npm on Ubuntu 20.04

### ISSUE THREAD

**Issue by arjunv27** [purescript/documentation#342]
```
  Error: Command failed with exit code 2 (ENOENT): stack --allow-different-user 
--numeric-version
spawn stack ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

```
using node 12.18 and npm 6.14

Does purescript require stack as a dependency?

**Comment by arjunv27** [comment]
hmm it does -- may be useful to add to the docs

**Comment by hdgarrood** [comment]
It only requires stack if the binaries don’t work. Since you’re on ubuntu 20.04, my guess is that you just need to install libtinfo5.

**Comment by arjunv27** [comment]
Yes, thanks -- got it to work.

Using Ubuntu these past few days has made me grow appreciative of Nix.
