### ISSUE TITLE
Make it more obvious that you have to install lists in the Getting Started guide

### ISSUE THREAD

**Issue by WildYorkies** [purescript/documentation#37]
I cannot import Data.List or Data.Foldable. Neither of them even show up on the list of modules that I can possibly import.

I followed the Getting Started guide exactly up to that point.

**Comment by LiamGoodacre** [comment]
What happened when you ran the command from __Installing Dependencies__?

**Comment by WildYorkies** [comment]
Ah, I see that now. 

```
Installing Dependencies

Dependencies can be installed using Bower:

bower install purescript-lists --save
```

I might suggest making the wording of this more explicit. It doesn't say "do this step" like the other steps. It just says "this is how you install dependencies".

**Comment by hdgarrood** [comment]
I think this does seem worth addressing, we just haven't gotten around to it yet. Shall we keep this open?

**Comment by Unisay** [comment]
I have also stumbled upon the same issue, but quickly figured out myself that example `bower install purescript-lists --save` is actually required for the subsequent commands to work.

I suggest making it more explicit that  `bower install purescript-lists --save` is a mandatory step for those who follows the examples in his repl.
