### ISSUE TITLE
ScopeConflict documentation cites `id`

### ISSUE THREAD

**Issue by mengwong** [purescript/documentation#408]
https://github.com/purescript/documentation/blob/master/errors/ScopeConflict.md talks about "id", but that's become "identity".

Action: think of a different illustration.

**Comment by thomashoneyman** [comment]
We should at least change the example to use `identity`

**Comment by elliotfayman** [comment]
I could take this issue if you would like.

**Comment by JordanMartinez** [comment]
Go for it!

**Comment by elliotfayman** [comment]
Ok I created a pull request here #442

**Comment by elliotfayman** [comment]
Glad I could help!

**Comment by JordanMartinez** [comment]
Thanks again!
