### ISSUE TITLE
Differences from Haskell: Records example - Could not match type Int with Number

### ISSUE THREAD

**Issue by d023604** [purescript/documentation#444]
Whilst following the documentation at [https://github.com/purescript/documentation/blob/master/language/Differences-from-Haskell.md#records](url), I receive the error `Could not match type Int with type Number`. 

The type PointRec is defined as  `type PointRec = { x :: Number, y :: Number }.` 

Yet the example usage is 
```
origin :: PointRec 
origin = { x: 0, y: 0 }
```
resulting in the type mismatch.

Suggest perhaps `origin = { x: 0.0 , y: 0.0} ` ?

**Comment by JordanMartinez** [comment]
Yeah, that's need to be fixed and your suggestion is correct.

**Comment by JordanMartinez** [comment]
Closed by #445
