### ISSUE TITLE
Pattern matching - guards not compiling

### ISSUE THREAD

**Issue by pietro909** [purescript/documentation#62]
The [code for guards example](https://github.com/purescript/documentation/blob/master/language/Pattern-Matching.md#guards) doesn't compile:

```purescript
evens :: List Int -> Int
evens Nil = 0
evens (Cons x xs) | x % 2 == 0 = 1 + evens xs
evens (Cons _ xs) = evens xs
```

It gives:

```
Error 1 of 1

  Could not match type

    Int

  with type

    Number


while checking that type t0
  is at least as general as type Number
while checking that expression x
  has type Number
while checking the type of a guard clause
in binding group evens

where t0 is an unknown type
```

**Comment by hdgarrood** [comment]
Thanks for the report! I think when this was updated to use `Int` rather than `Number`, the person who did it must have missed that `%` only works for `Number`. That use of `%` should be changed to `mod`.
