### ISSUE TITLE
Delete the old wiki

### ISSUE THREAD

**Issue by paf31** [purescript/documentation#78]
Now seems like a good time to remove the outdated content from the wiki. We should probably keep it active though, with links to the updated material.

**Comment by hdgarrood** [comment]
I went ahead and did this. If any wiki page corresponded to a file in this repo, I updated its contents to just point to the page in this repo; if the page was out of date, I simply deleted it (there weren't many of these though).

It's just the following pages left which I'm not sure what to do with:

* PureScript-Conf-2016.md
* PureScript-Presentations.md
* Home.md
* 0.7-Migration-Guide.md
* PureScript-Conf-2015.md
* Wikipedia-Page-Proposal.md

**Comment by paf31** [comment]
Thanks very much! I say just delete them, they're in the Git history if we ever need them, and none of them are immediately useful for new users.
