### ISSUE TITLE
Find place to put TIL-style info

### ISSUE THREAD

**Issue by chexxor** [purescript/documentation#85]
One part of learning a language is idioms. One way to learn a language's idioms is by seeing alternate ways of writing a thing.

For example:
- people first learn `logShow`, then discover `traceAny`.
- people first learn "do-notation", then discover that using `>>=`, `<$>`, and maybe `>=>` is a better way.
- people first learn records, then discover ADTs and lens are better.
- people first learn `ContT`, then discover `Aff` is better, or vice-versa.
- people first learn `Either MultipleErrors a`, then discover clever use of `ExceptT` is a bit better.
- people first use simple recursion, then discover `MonadRec` or fix-point concepts are very helpful.

These TILs would need to be structured, somehow. Perhaps by problem category?
- Debugging
- Parsing
- Error-handling
- Data structures

Perhaps these TILs could be integrated into another hierarchy of docs, like alongside a curriculum having practice exercises for introducing these problem categories?

**Comment by hdgarrood** [comment]
I'd rather leave this to libraries, honestly. I think we would be biting off a bit more than we could chew if we included all this in this repository, and I think it would be particularly at risk of getting out of date.

**Comment by hdgarrood** [comment]
Also I wouldn't agree that any of these things are "better" than the others, some are just more appropriate in certain contexts. `ContT` has something that `Aff` doesn't in that you can use it in a non-effectful transformer stack, for instance.

**Comment by chexxor** [comment]
I don't disagree.

What's the scope of this repo, from your view? I don't think it's been discussed yet. Just PureScript language reference? Also teaching PureScript ecosystem and its concepts like type classes? Most reasonable things that aren't at risk of becoming out of date?

**Comment by chexxor** [comment]
Right, I would expect these docs would include describing the situations in which one starts to look for alternative solutions.

**Comment by hdgarrood** [comment]
In my mind, this repo is mainly for the language guide and the docs about each compiler error, plus a few other things that don't neatly fit anywhere else. If it makes sense to put some docs together with some code so that it appears on Pursuit, I think that's probably the best place for it. So for example — this has only just occurred to me, as it happens — I'd quite like to move the Partial guide to `purescript-partial`.

**Comment by chexxor** [comment]
Yeah, that sounds reasonable. We could still have a TIL thing, but find a different home for it.

Would you say a PS curriculum would be out-of-scope for this repo? Seems like it would be. If that's the case, I'll create a new repo to host that, and I'd likely put the Intro to Prelude series in there.

**Comment by hdgarrood** [comment]
I'm not sure I completely understand what you are imagining but I think so, yeah. Creating a new repo works, but I think it would be worth considering whether it would make sense to add things to the existing Prelude docs too.
