### ISSUE TITLE
Getting started: no type declaration for main

### ISSUE THREAD

**Issue by i3games** [purescript/documentation#87]
[invoking `pulp run`](https://github.com/purescript/documentation/blob/master/guides/Getting-Started.md#creating-executables) in the Getting Started guide throws a warning ` No type declaration was provided for the top-level declaration of main....`

**Comment by chexxor** [comment]
We can fix this by adding the type signature to that function, something like `main :: forall e. Eff (console :: CONSOLE | e) Unit`, but that might require explaining `Eff`, which doesn't belong in "Getting Started".

@i3games How do you propose this be fixed?

**Comment by i3games** [comment]
I just added pull request #90 which does add type declarations. If a compiler complains about something by default, I think it is better to confront beginners with learning about these concepts instead of saying "ignore these warnings".

**Comment by chexxor** [comment]
I can accept that reasoning. We should wait for other people to review this solution before accepting it.

@i3games Thanks so much for reporting these issues, and even fixing them!

**Comment by i3games** [comment]
You're welcome. I'd like to help out with documentation in the future as I'm getting more into PS.
