### ISSUE TITLE
Getting started: more warnings about missing type declarations

### ISSUE THREAD

**Issue by i3games** [purescript/documentation#88]
Invoking [pulp build](https://github.com/purescript/documentation/blob/master/guides/Getting-Started.md#compiling-a-solution) throws 3 more `missing type declarations` warnings #87 for Euler.purs

**Comment by hdgarrood** [comment]
Fixed by https://github.com/purescript/documentation/commit/3b20d93be82b2f6b65645e2108816f879d858539
