### ISSUE TITLE
installing PS on Linux (Ubuntu and/or Mint) 

### ISSUE THREAD

**Issue by MatrixMike** [purescript/documentation#99]
(ref from https://github.com/purescript/purescript/issues/2819) If it has been fixed then what is the entry point for installing PS on Linux (Ubuntu or Mint etc) ? My searches for guides to install have yielded misleading and contradicting directions. Why do the instructions on the web-page you mention force you into nodejs etc. What OS was your beginner using? I can try using the same as I have plenty of spare hardware here. I managed to compile some simple very crude .psc files into js which is a good start. I built the compiler from scratch - at least then I can see some of the structure and see where is puts the executable. I guess that I am doing it hard but now that I have found that it compiles at least some .psc code I am quite excited to continue. The code that I compiled was done on geany (very quick, flexible and handy) but I could not include any imports. I guess pulp etc would setup an environment for me...

**Comment by hdgarrood** [comment]
> My searches for guides to install have yielded misleading and contradicting directions.

could you be more specific? Which guides have you tried and which directions were misleading?

> Why do the instructions on the web-page you mention force you into nodejs etc.

Because much of the tooling we use is written in PureScript or JavaScript. Using PureScript without Node is possible but it's a lot more effort, so I don't recommend it.
